
name: Deploy to Server

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
    - name: print
      run: echo ${GITHUB_REF#refs/heads/}
    - name: Git Checkout Latest
      uses: actions/checkout@v2
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
    - name: Deploy to VPS
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          sudo su
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cosmos-explorer:latest
          docker run -d --name cosmos-explorer -p 5001:80 ${{ secrets.DOCKERHUB_USERNAME }}/cosmos-explorer:latest
        EOF